/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.alfabattle.kafka.rest.client.model;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * UserPaymentAnalytic
 */
public class UserPaymentAnalytic {

    private Map<String, PaymentCategoryInfo> analyticInfo = null;

    private BigDecimal totalSum = null;

    private String userId = null;

    public UserPaymentAnalytic analyticInfo(Map<String, PaymentCategoryInfo> analyticInfo) {
        this.analyticInfo = analyticInfo;
        return this;
    }

    public UserPaymentAnalytic putAnalyticInfoItem(String key, PaymentCategoryInfo analyticInfoItem) {
        if (this.analyticInfo == null) {
            this.analyticInfo = new HashMap<String, PaymentCategoryInfo>();
        }
        this.analyticInfo.put(key, analyticInfoItem);
        return this;
    }

    /**
     * Get analyticInfo
     *
     * @return analyticInfo
     **/
    public Map<String, PaymentCategoryInfo> getAnalyticInfo() {
        return analyticInfo;
    }

    public void setAnalyticInfo(Map<String, PaymentCategoryInfo> analyticInfo) {
        this.analyticInfo = analyticInfo;
    }

    public UserPaymentAnalytic totalSum(BigDecimal totalSum) {
        this.totalSum = totalSum;
        return this;
    }

    /**
     * Get totalSum
     *
     * @return totalSum
     **/
    public BigDecimal getTotalSum() {
        return totalSum;
    }

    public void setTotalSum(BigDecimal totalSum) {
        this.totalSum = totalSum;
    }

    public UserPaymentAnalytic userId(String userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Get userId
     *
     * @return userId
     **/
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserPaymentAnalytic userPaymentAnalytic = (UserPaymentAnalytic) o;
        return Objects.equals(this.analyticInfo, userPaymentAnalytic.analyticInfo) &&
                Objects.equals(this.totalSum, userPaymentAnalytic.totalSum) &&
                Objects.equals(this.userId, userPaymentAnalytic.userId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(analyticInfo, totalSum, userId);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserPaymentAnalytic {\n");

        sb.append("    analyticInfo: ").append(toIndentedString(analyticInfo)).append("\n");
        sb.append("    totalSum: ").append(toIndentedString(totalSum)).append("\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

