/*
 * Сервис проверки статуса банкоматов
 * Сервис, возвращающий информацию о банкоматах Альфа-Банка
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@alfabank.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.alfabattle.atm.alfaclient.client.model;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ATMAccess
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-27T12:01:57.891Z")
public class ATMAccess {
  /**
   * Доступность АТМ для клиента, принимает следующие значения:  alltime &#x3D; круглосуточно  schedule &#x3D; по расписанию работы организации. В этом случае расписание указывается в поле schedule.
   */
  @JsonAdapter(ModeEnum.Adapter.class)
  public enum ModeEnum {
    ALLTIME("alltime"),
    
    SCHEDULE("schedule"),
    
    NOINFO("noinfo");

    private String value;

    ModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ModeEnum fromValue(String text) {
      for (ModeEnum b : ModeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ModeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ModeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("mode")
  private ModeEnum mode = null;

  @SerializedName("schedule")
  private String schedule = null;

  public ATMAccess mode(ModeEnum mode) {
    this.mode = mode;
    return this;
  }

   /**
   * Доступность АТМ для клиента, принимает следующие значения:  alltime &#x3D; круглосуточно  schedule &#x3D; по расписанию работы организации. В этом случае расписание указывается в поле schedule.
   * @return mode
  **/
  @ApiModelProperty(value = "Доступность АТМ для клиента, принимает следующие значения:  alltime = круглосуточно  schedule = по расписанию работы организации. В этом случае расписание указывается в поле schedule.")
  public ModeEnum getMode() {
    return mode;
  }

  public void setMode(ModeEnum mode) {
    this.mode = mode;
  }

  public ATMAccess schedule(String schedule) {
    this.schedule = schedule;
    return this;
  }

   /**
   * Указывается, если mode&#x3D;schedule. Массив [DD:hhmm–hhmm,DD:hhmm–hhmm,DD:hhmm–hhmm,…] DD &#x3D; [MO, TU, WE, TH, FR, SA, SU] hh &#x3D; 00..24 mm &#x3D; 00..59 Время указывается местное (места установки АТМ) Если в течение дня есть перерыв, то указывается каждый диапазон времени в течение одного дня. Например, MO:0800-1300,MO:1400-2100,TU:0800-1300,TU:1400-2100
   * @return schedule
  **/
  @ApiModelProperty(value = "Указывается, если mode=schedule. Массив [DD:hhmm–hhmm,DD:hhmm–hhmm,DD:hhmm–hhmm,…] DD = [MO, TU, WE, TH, FR, SA, SU] hh = 00..24 mm = 00..59 Время указывается местное (места установки АТМ) Если в течение дня есть перерыв, то указывается каждый диапазон времени в течение одного дня. Например, MO:0800-1300,MO:1400-2100,TU:0800-1300,TU:1400-2100")
  public String getSchedule() {
    return schedule;
  }

  public void setSchedule(String schedule) {
    this.schedule = schedule;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ATMAccess atMAccess = (ATMAccess) o;
    return Objects.equals(this.mode, atMAccess.mode) &&
        Objects.equals(this.schedule, atMAccess.schedule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mode, schedule);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ATMAccess {\n");
    
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

