/*
 * Сервис проверки статуса банкоматов
 * Сервис, возвращающий информацию о банкоматах Альфа-Банка
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@alfabank.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.alfabattle.atm.alfaclient.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * SupportInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-27T12:01:57.891Z")
public class SupportInfo {
  @SerializedName("email")
  private String email = null;

  @SerializedName("other")
  private String other = null;

  @SerializedName("phone")
  private String phone = null;

  public SupportInfo email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Адрес электронной почты
   * @return email
  **/
  @ApiModelProperty(value = "Адрес электронной почты")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public SupportInfo other(String other) {
    this.other = other;
    return this;
  }

   /**
   * Иные контакты поддержки
   * @return other
  **/
  @ApiModelProperty(value = "Иные контакты поддержки")
  public String getOther() {
    return other;
  }

  public void setOther(String other) {
    this.other = other;
  }

  public SupportInfo phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Телефон
   * @return phone
  **/
  @ApiModelProperty(value = "Телефон")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SupportInfo supportInfo = (SupportInfo) o;
    return Objects.equals(this.email, supportInfo.email) &&
        Objects.equals(this.other, supportInfo.other) &&
        Objects.equals(this.phone, supportInfo.phone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, other, phone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupportInfo {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    other: ").append(toIndentedString(other)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

